Extend XPT2046 touch driver to add temperature, batt voltage, aux input voltage read support
espressif/esp-iot-solution pull request #236
Opened 2022-12-08 06:11 UTC by dvosully

The XPT2046 touch controller chip (and variants) supports reading temperature, battery voltage and auxiliary input voltage.

This patch extends the XPT2046 driver with functions to read these values. Tested with the TSC2046 chip (equivalent).

2022-12-23 09:42 UTC, Lzw655 requested changes
@dvosully Hi, It's very nice to add three extra functions for XPT2046. Thanks for your contributions! And I left some suggestions, PTAL.

2022-12-23 09:42 UTC, Lzw655 commented on components/display/touch_panel/xpt2046/xpt2046.c
> +
```suggestion
    TOUCH_CHECK(ESP_OK == ret, "Vref turn off failed", ESP_FAIL);

```

2022-12-23 09:42 UTC, Lzw655 commented on components/display/touch_panel/xpt2046/xpt2046.c
> +
```suggestion
    TOUCH_CHECK(ESP_OK == ret, "Vref turn off failed", ESP_FAIL);
    
```

2022-12-23 09:42 UTC, Lzw655 commented on components/display/touch_panel/xpt2046/xpt2046.c
> +
```suggestion
    TOUCH_CHECK(ESP_OK == ret, "Vref turn off failed", ESP_FAIL);
    
```

2022-12-23 09:42 UTC, Lzw655 commented on components/display/touch_panel/xpt2046/xpt2046.h
> +esp_err_t xpt2046_get_aux_v(float* temperature);
Please modify the descriptions and the name of argument for these two APIs.

2022-12-24 02:18 UTC, dvosully commented
Thanks, I have incorporated your suggested improvements.

2022-12-30 08:25 UTC, Lzw655 approved these changes
Nice work, can be merged!

2022-12-30 12:34 UTC, closed without merging